export const EMPLOYEE_CREAT_REQUESTE = 'Employee_CREATE_REQUEST';
export const EMPLOYEE_CREATE_SUCCESS='EMPLOYEE_CREATE_SUCCESS';
export const EMPLOYEE_CREATE_FAIL='EMPLOYE_CREATE_FAIL';
export const EMPLOYEE_LIST_REQUEST='EMPLOYEE_LIST_REQUEST';
export const EMPLOYEE_LIST_SUCCESS='EMPLOYEE_LIST_SUCCESS';
export const EMPLOYEE_LIST_FAIL='EMPLOYEE_LIST_FAIL'

export const EMPLOYEE_DETAIL_REQUEST='EMPLOYEE_DETAIL_REQUEST'
export const EMPLOYEE_DETAIL_SUCCESS='EMPLOYEE_DETAIL_SUCCESS'
export const EMPLOYEE_DETAIL_FAIL='EMPLOYEE_DETAIL_FAIL'
export const UPDATE_EMPLOYEE_REQUEST='UPDATE_EMPLOYEE_REQUEST'
export const UPDATE_EMPLOYEE_SUCCESS='UPDATE_EMPLOYEE_SUCCESS'
export const UPDATE_EMPLOYEE_FAIL='UPDATE_EMPLOYEE_FAIL'

export const EMPLOYEE_DELETE_REQUEST='EMPLYEE_DELETE_REQUEST'
export const EMPLOYEE_DELETE_SUCCESS='EMPLYEE_DELETE_SUCCESS'
export const EMPLOYEE_DELETE_FAIL='EMPLYEE_DELETE_FAIL'