export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';
export const ORDER_UPDATE_FAIL='ORDER_UPDATE_FAIL';
export const ORDER_UPDATE_REQUEST='ORDER_UPDATE_REQUEST'
export const ORDER_UPDATE_SUCCESS='ORDER_UPDATE_SUCCESS'


export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST';
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS';
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL';
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';



export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';
export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET';


export const ORDER_LOG_REQUEST='ORDER_LOG_REQUES'
export const ORDER_LOG_SUCCESS='ORDER_LOG_SUCCESS'
export const ORDER_LOG_FAIL='ORDER_LOG_FAIL'

export const ORDER_LOG_DELETE_REQUEST='ORDER_LOG_DELETE_REQUEST'
export const ORDER_LOG_DELETE_FAIL='ORDER_LOG_DELETE_FAIL'
export const ORDER_LOG_DELETE_SUCCESS='ORDER_LOG_DELETE_SUCCESS'

export const ORDER_GD_STATUS_REQUEST='ORDER_GD_STATUS_REQUEST'
export const ORDER_GD_STATUS_SUCCESS='ORDER_GD_STATUS_SUCCESS'
export const ORDER_GD_STATUS_FAIL='ORDER_GD_STATUS_FAIL'


export const ORDER_QUANTITY_UPDATE_REQUEST='ORDER_QUANTITY_UPDATE_REQUEST'
export const ORDER_QUANTITY_UPDATE_SUCCESS='ORDER_QUANTITY_UPDATE_SUCCESS'
export const ORDER_QUANTITY_UPDATE_FAIL='ORDER_QUANTITY_UPDATE_FAIL'




