export  const REPORT_CREATE_REQUEST='REPORT_CREATE_REQUES';
export const REPORT_CREATE_SUCCESS='REPORT_CREATE_REQUES';
export const REPORT_CREATE_FAIL='REPORT_CREATE_FAIL';
export const REPORT_LIST_SUCCESS='REPORT_LIST_SUCCESS'
