export const SERVICE_TYPE_CREATE_REQUEST='SERVICE_TYPE_CREATE_REQUEST';
export const SERVICE_TYPE_CREATE_SUCCESS='SERVICE_TYPE_CREATE_SUCCESS'
export const SERVICE_TYPE_CREATE_FAIL='SERVICE_TYPE_CREATE_FAIL'
export const SERVICE_TYPE_LIST_REQUEST='SERVICE_TYPE_LIST_REQUEST'
export const SERVICE_LIST_SUCCESS='SERVICE_LIST_SUCCESS'
export const SERVICE_TYPE_LIST_FAIL='SERVICE_TYPE_LIST_FAIL'

export const SERVICE_TYPE_DETAIL_REQUEST='SERVICE_TYPE_DETAIL_REQUEST'
export const SERVICE_TYPE_DETAIL_SUCCESS='SERVICE_TYPE_DETAIL_SUCCESS'
export const SERVICE_TYPE_DETAIL_FAIL='SERVICE_TYPE_DETAIL_SUCCESS'

export const SERVICE_UPDATE_REQUEST='SERVICE_UPDATE_REQUEST'
export const SERVICE_UPDATE_SUCCESS='SERVICE_UPDATE_SUCCESS'
export const SERVICE_UPDATE_FAIL='SERVICE_UPDATE_FAIL'

export const SERVICE_DELETE_REQUEST='SERVICE_DELETE_REQUEST'
export const SERVICE_DELETE_SUCCESS='SERVICE_DELETE_SUCCESS'
export const SERVICE_DELETE_FAIL='SERVICE_DELETE_FAIL'


